# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            TraqBio
tagline:          'Flexible progress tracking for core unit projects'
description:      'Flexible progress tracking for core unit projects'
url:              http://sysbio-bioinf.github.io/TraqBio
baseurl:          /

author:
  name:           'Medical Systems Biology, Ulm University'
  url:            http://sysbio.uni-ulm.de/

include:          ['_pages']


# Custom vars
version:          1.3.6

github:
  repo:           https://github.com/sysbio-bioinf/TraqBio
